import React, { useState, useEffect } from 'react';
import { DollarSign, Eye, AlertCircle, RefreshCw, Loader } from 'lucide-react';
import SalarySlipModal from './SalarySlipModal';
import { salaryAPI } from '../../utils/api';

const SalaryHistory = () => {
  const [salarySlips, setSalarySlips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedSlip, setSelectedSlip] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  // Fetch salary slips on component mount
  useEffect(() => {
    fetchSalarySlips();
  }, []);

  const fetchSalarySlips = async (bypassCache = false) => {
    setLoading(true);
    setError('');
    try {
      const response = await salaryAPI.getMySalarySlips({ bypassCache });
      
      // Handle response structure
      const slipsData = response?.data || response;
      setSalarySlips(Array.isArray(slipsData) ? slipsData : []);
    } catch (err) {
      console.error('Error fetching salary slips:', err);
      setError(err.message || 'Failed to load salary slips. Please try again.');
      setSalarySlips([]);
    } finally {
      setLoading(false);
    }
  };

  const handleViewSlip = (slip) => {
    setSelectedSlip(slip);
    setIsModalOpen(true);
  };

  const handleRefresh = async () => {
    try {
      console.log('🔄 Refreshing salary slips...');
      await fetchSalarySlips(true);  // Bypass cache
      console.log('✓ Salary slips refreshed successfully');
    } catch (err) {
      console.error('❌ Failed to refresh salary slips:', err);
    }
  };

  // Format date to readable format
  const formatDate = (dateString) => {
    try {
      const date = new Date(dateString);
      return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long' });
    } catch {
      return dateString;
    }
  };

  // Format currency
  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 2
    }).format(amount || 0);
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-64">
        <Loader className="w-8 h-8 text-blue-600 animate-spin mb-3" />
        <p className="text-gray-600">Loading salary slips...</p>
      </div>
    );
  }

  return (
    <div className="w-full bg-white rounded-lg shadow-md overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-blue-700 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <DollarSign className="w-6 h-6 text-white" />
          <h2 className="text-2xl font-bold text-white">Salary History</h2>
        </div>
        <button
          onClick={handleRefresh}
          disabled={loading}
          className="bg-white bg-opacity-20 hover:bg-opacity-30 text-white px-3 py-2 rounded-md flex items-center gap-2 transition-all disabled:opacity-50"
          title="Refresh salary slips"
        >
          <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {/* Content */}
      <div className="p-6">
        {error && (
          <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-lg flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-semibold text-red-900">Error</p>
              <p className="text-red-700 text-sm">{error}</p>
            </div>
          </div>
        )}

        {salarySlips.length === 0 ? (
          <div className="text-center py-12">
            <DollarSign className="w-12 h-12 text-gray-300 mx-auto mb-3" />
            <p className="text-gray-600 text-lg font-medium">No salary slips available</p>
            <p className="text-gray-500 text-sm">Your salary records will appear here once generated by admin</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b-2 border-gray-200">
                  <th className="text-left py-3 px-4 font-semibold text-gray-700">Month</th>
                  <th className="text-right py-3 px-4 font-semibold text-gray-700">Base Salary</th>
                  <th className="text-right py-3 px-4 font-semibold text-gray-700">Bonuses</th>
                  <th className="text-right py-3 px-4 font-semibold text-gray-700">Deductions</th>
                  <th className="text-right py-3 px-4 font-semibold text-gray-700">Net Pay</th>
                  <th className="text-center py-3 px-4 font-semibold text-gray-700">Actions</th>
                </tr>
              </thead>
              <tbody>
                {salarySlips.map((slip) => (
                  <tr
                    key={slip._id}
                    className="border-b border-gray-100 hover:bg-gray-50 transition-colors"
                  >
                    <td className="py-4 px-4 text-gray-900 font-medium">
                      {formatDate(slip.month)}
                    </td>
                    <td className="py-4 px-4 text-right text-gray-700">
                      {formatCurrency(slip.baseSalary)}
                    </td>
                    <td className="py-4 px-4 text-right text-green-600 font-medium">
                      {formatCurrency(slip.bonuses)}
                    </td>
                    <td className="py-4 px-4 text-right text-red-600 font-medium">
                      {formatCurrency(slip.deductions)}
                    </td>
                    <td className="py-4 px-4 text-right text-blue-600 font-bold text-lg">
                      {formatCurrency(slip.netPay)}
                    </td>
                    <td className="py-4 px-4 text-center">
                      <button
                        onClick={() => handleViewSlip(slip)}
                        className="inline-flex items-center gap-2 bg-blue-100 hover:bg-blue-200 text-blue-700 px-3 py-1.5 rounded-md transition-colors font-medium"
                        title="View details"
                      >
                        <Eye className="w-4 h-4" />
                        View
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Salary Slip Modal */}
      {selectedSlip && (
        <SalarySlipModal
          isOpen={isModalOpen}
          onClose={() => {
            setIsModalOpen(false);
            setSelectedSlip(null);
          }}
          salarySlip={selectedSlip}
        />
      )}
    </div>
  );
};

export default SalaryHistory;
